package main

const indexHTML = `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LinkVideo Monitor</title>
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<style>
:root{--bg:#f4f5f7;--card:#fff;--line:#dfe3e8;--text:#20252b;--muted:#69727c;--dark:#414346;--orange:#ffad19;--orange2:#eb9600;--green:#168f4a;--red:#bd3737;--blue:#3b73c5;--shadow:0 10px 28px rgba(30,39,48,.07)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px "Segoe UI",Arial,sans-serif}button,input,select{font:inherit}button{color:inherit}
.top{height:68px;background:var(--dark);color:#fff;position:sticky;top:0;z-index:30}.topin{max-width:1260px;height:68px;margin:auto;padding:0 22px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:11px;font-size:22px;font-weight:720}.logo{width:31px;height:31px;position:relative}.logo:before,.logo:after{content:"";position:absolute;transform:rotate(45deg)}.logo:before{width:18px;height:18px;background:var(--orange);left:3px;top:8px}.logo:after{width:12px;height:12px;background:#c9cccf;left:17px;top:3px}.brand-product{font:inherit;font-size:inherit;font-weight:inherit;letter-spacing:0;color:#fff}.topactions{display:flex;align-items:center;gap:18px}.statusline{display:flex;align-items:center;gap:9px}.dot{width:10px;height:10px;border-radius:50%;background:#9ca2a8}.dot.ok{background:#31c66d;box-shadow:0 0 0 4px rgba(49,198,109,.15)}.dot.wait{background:#f3b330}.dot.bad{background:#ef6767}
.wrap{max-width:1260px;margin:24px auto 102px;padding:0 22px}.intro{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:16px}.intro h1{font-size:26px;margin:0 0 4px}.muted{color:var(--muted);line-height:1.45}.grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:16px;align-items:start}.stack{display:flex;flex-direction:column;gap:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:19px;box-shadow:var(--shadow)}.head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:15px}.head h2{font-size:17px;margin:0}.head p{margin:3px 0 0}.row2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.row3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}label.field{display:block;color:#505a64;font-size:13px;margin:11px 0 6px}input[type=text],input[type=password],input[type=number],select{width:100%;min-height:40px;padding:9px 10px;border:1px solid #cfd5dc;border-radius:8px;background:#fff;outline:none}input:focus,select:focus{border-color:var(--orange2);box-shadow:0 0 0 3px rgba(235,150,0,.12)}input:disabled,select:disabled{background:#f0f2f4;color:#8b9299}.hidden{display:none!important}
.modegrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.modegrid.capturegrid{grid-template-columns:repeat(2,1fr)}.mode{display:block;border:1px solid var(--line);border-radius:11px;padding:13px;cursor:pointer;background:#fff}.mode.active{border-color:var(--orange2);background:#fff9ec;box-shadow:0 0 0 2px rgba(235,150,0,.12)}.mode input{display:none}.mode strong{display:block;margin-bottom:4px}.mode span{font-size:12px;color:var(--muted)}
.btn{border:1px solid #cdd3d9;background:#fff;border-radius:8px;padding:9px 12px;cursor:pointer}.btn:hover{background:#f5f6f7}.btn.primary{background:var(--orange);border-color:var(--orange2);font-weight:700}.btn.stop{color:#a42d2d;background:#fff2f2;border-color:#e3b3b3}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.linkline{display:flex;gap:8px}.linkline>*:first-child{flex:1}.check{display:flex;gap:9px;align-items:flex-start;margin:12px 0;cursor:pointer}.check input{margin-top:3px;accent-color:var(--orange2)}.hint{margin-top:10px;padding:10px 11px;border-radius:8px;background:#f7f8fa;color:var(--muted);font-size:12.5px;line-height:1.45}.sectionline{height:1px;background:#eceef1;margin:16px 0}
.profiles{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.profiles.audio-profiles{grid-template-columns:repeat(3,1fr)}.profile{border:1px solid var(--line);border-radius:10px;padding:11px;text-align:left;background:#fff;cursor:pointer}.profile.active{border-color:var(--orange2);background:#fff9ec;box-shadow:0 0 0 2px rgba(235,150,0,.12)}.profile b{display:block}.profile small{color:var(--muted)}
.monitor-layout{position:relative;height:270px;margin-top:12px;border:1px solid var(--line);border-radius:12px;background:#eef1f4;overflow:hidden}.monitor-card{position:absolute;display:flex;align-items:center;justify-content:center;gap:8px;padding:8px;border:2px solid transparent;border-radius:11px;background:#fff;cursor:pointer;text-align:left;box-shadow:inset 0 0 0 1px var(--line)}.monitor-card:hover{background:#f8f9fa}.monitor-card.selected{border-color:var(--orange2);background:#fff9ec;box-shadow:0 0 0 2px rgba(235,150,0,.12)}.monitor-icon{width:38px;height:29px;border:2px solid #707983;border-radius:5px;display:grid;place-items:center;background:#eef1f4;color:#4c5660;font-weight:750;flex:0 0 auto}.monitor-meta{min-width:0}.monitor-meta b,.monitor-meta span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.monitor-meta span{color:var(--muted);font-size:12px;margin-top:3px}
.badge{display:inline-block;padding:4px 8px;border-radius:99px;background:#eceff2;color:#5c6570;font-size:12px}.summary{line-height:1.55}.summary-row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #eef0f2}.summary-row:last-child{border-bottom:0}.summary-row span{color:var(--muted);text-align:right}.sidebar-sticky{position:sticky;top:84px;display:flex;flex-direction:column;gap:12px}.footer-save{font-weight:700}.footer-save.saving{opacity:.65;cursor:wait}
.message{position:fixed;right:22px;top:82px;z-index:60;max-width:430px;padding:12px 15px;border-radius:9px;background:#24292e;color:#fff;box-shadow:0 12px 35px rgba(0,0,0,.23);display:none}.message.show{display:block}.message.error{background:#a73535}.dev summary{cursor:pointer;font-weight:680}.devbox{margin-top:15px}.log{white-space:pre-wrap;word-break:break-word;max-height:320px;overflow:auto;background:#171a1e;color:#d9dee3;border-radius:9px;padding:12px;font:12px Consolas,monospace}.smallvalue{padding:9px 10px;border:1px solid var(--line);border-radius:8px;background:#f7f8f9;word-break:break-all}
.bottom{position:fixed;left:0;right:0;bottom:0;background:rgba(255,255,255,.96);border-top:1px solid #d8dde2;backdrop-filter:blur(8px);z-index:35}.bottomin{max-width:1260px;margin:auto;padding:11px 22px;display:flex;align-items:center;justify-content:space-between;gap:14px}.bottomactions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.recordstate{font-weight:650}
@media(max-width:920px){.grid{grid-template-columns:1fr}.sidebar-sticky{position:static}.profiles{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.topin{padding:0 12px}.topactions{gap:8px}.statusline{display:none}.row2,.row3,.modegrid,.profiles{grid-template-columns:1fr}.monitor-layout{height:220px}.intro{align-items:flex-start;flex-direction:column}.bottomin{align-items:flex-start}.bottomactions{flex-wrap:wrap;justify-content:flex-end}}
</style>
</head>
<body>
<div class="top"><div class="topin"><div class="brand"><div class="logo"></div><div><span>LinkVideo</span> <span class="brand-product">Monitor</span></div></div><div class="topactions"><div class="statusline"><span id="statusDot" class="dot"></span><span id="statusText">загрузка…</span></div></div></div></div>
<div id="message" class="message"></div>
<div class="wrap">
<div class="intro"><div><h1>Трансляция экрана</h1></div><span id="version" class="badge"></span></div>
<div class="grid"><main class="stack">

<section class="card"><div class="head"><div><h2>Подключение</h2><p class="muted">Куда отправлять поток</p></div></div>
<div class="modegrid">
<label class="mode" id="remoteMode"><input type="radio" name="output_mode" value="remote"><strong>Сервер LinkVideo</strong><span>Передача трансляции в облако.</span></label>
<label class="mode" id="localMode"><input type="radio" name="output_mode" value="local"><strong>Локальная RTSP-трансляция</strong><span>Готовая ссылка для подключения в LinkVideo Server.</span></label>
</div>
<div id="remotePanel"><label class="field">Ссылка подключения</label><div class="linkline"><input id="link" type="password" placeholder="linkvideomonitor:…"><button class="btn" onclick="toggleLink()">Показать</button></div><div class="row2"><div><label class="field">Протокол передачи</label><select id="protocol"><option value="rtsp">RTSP / TCP</option><option value="rtmp">RTMP</option></select></div><div><label class="field">Проверка</label><button class="btn" style="width:100%" onclick="testConnection()">Проверить сервер</button></div></div></div>
<div id="localPanel" class="hidden"><label class="field">Порт</label><input id="local_rtsp_port" type="number" min="1" max="65535"><input id="local_rtsp_path" type="hidden" value="screen"><label class="field">RTSP-ссылка</label><div class="linkline"><div id="localRTSPURL" class="smallvalue">—</div><button class="btn" onclick="copyText('localRTSPURL')">Копировать</button></div><div class="hint">Для подключения в LinkVideo Server.</div></div>
</section>

<section class="card"><div class="head"><div><h2>Источник изображения</h2><p class="muted">Что будет видно в трансляции</p></div></div>
<div class="modegrid capturegrid">
<label class="mode captureMode" data-mode="full"><input type="radio" name="capture_mode" value="full"><strong>Все экраны</strong><span>Весь рабочий стол со всеми подключёнными мониторами.</span></label>
<label class="mode captureMode" data-mode="monitor"><input type="radio" name="capture_mode" value="monitor"><strong>Выбранный монитор</strong><span>Передача изображения только с одного экрана.</span></label>
</div>
<div id="monitorPanel" class="hidden"><div id="monitorGrid" class="monitor-layout"></div><div class="hint">Мониторы расположены так же, как в параметрах дисплея Windows.</div><input id="monitor_index" type="hidden"><input id="monitor_number" type="hidden"></div>
<label class="check"><input id="cursor" type="checkbox">Показывать курсор мыши</label>
<label class="check"><input id="privacy_protection" type="checkbox">Скрывать пароли, PIN и чувствительные данные пикселизацией</label>
<div class="hint">Во время ввода программа закрывает поля в приложениях и на сайтах до кодирования и отправки на сервер.</div>
</section>

<section class="card"><div class="head"><div><h2>Качество изображения</h2><p class="muted">Разрешение, качество и плавность</p></div></div>
<label class="field">Разрешение трансляции</label><div class="profiles">
<button class="profile resolution-profile" data-resolution="original" onclick="setResolution('original')"><b>Исходное</b><small>Разрешение монитора</small></button>
<button class="profile resolution-profile" data-resolution="full_hd" onclick="setResolution('full_hd')"><b>Full HD</b><small>1920×1080</small></button>
<button class="profile resolution-profile" data-resolution="hd" onclick="setResolution('hd')"><b>HD</b><small>1280×720</small></button>
</div><input id="resolution_profile" type="hidden">
<label class="field">Качество передачи</label><div class="profiles">
<button class="profile" data-profile="economy" onclick="setProfile('economy')"><b>Экономный</b><small>256 Кбит/с</small></button>
<button class="profile" data-profile="fast" onclick="setProfile('fast')"><b>Быстрый</b><small>512 Кбит/с</small></button>
<button class="profile" data-profile="medium" onclick="setProfile('medium')"><b>Стандартный</b><small>1024 Кбит/с</small></button>
</div><input id="quality_profile" type="hidden">
<div class="row2"><div><label class="field">Частота кадров</label><select id="fps"><option value="10">10 кадров/с</option><option value="15">15 кадров/с</option><option value="20">20 кадров/с</option><option value="25">25 кадров/с</option></select></div><div><label class="field">Кодировщик</label><select id="encoder"><option value="auto">Автоматически</option><option value="h264_qsv">Intel Quick Sync</option><option value="h264_nvenc">NVIDIA NVENC</option><option value="h264_amf">AMD AMF</option><option value="libx264">Программный H.264</option></select></div></div>
<div class="hint">Автоматический режим проверяет кодировщик на текущем разрешении и сохраняет выбранный вариант. При подтверждённой ошибке используется программный H.264 без постоянных переключений.</div>
<input id="bitrate_kbps" type="hidden"><input id="maxrate_kbps" type="hidden"><input id="bufsize_kbps" type="hidden"><input id="preset" type="hidden">
</section>

<section class="card" id="audioCard"><div class="head"><div><h2>Звук компьютера</h2><p class="muted">Передача звука, который воспроизводится на компьютере</p></div></div>
<label class="check"><input id="audio_enabled" type="checkbox" onchange="audioChanged()">Передавать звук</label>
<div id="audioSettings"><label class="field">Качество звука</label><div class="profiles audio-profiles">
<button class="profile audio-profile" data-audio-profile="low" onclick="setAudioQuality('low')"><b>Базовое</b><small>64 Кбит/с</small></button>
<button class="profile audio-profile" data-audio-profile="medium" onclick="setAudioQuality('medium')"><b>Оптимальное</b><small>128 Кбит/с</small></button>
<button class="profile audio-profile" data-audio-profile="high" onclick="setAudioQuality('high')"><b>Высокое</b><small>192 Кбит/с</small></button>
</div><div class="hint">Передаётся звук приложений, браузера и Windows.</div></div>
<input id="audio_quality" type="hidden"><input id="audio_bitrate_kbps" type="hidden"><input id="audio_sample_rate" type="hidden" value="48000"><input id="audio_channels" type="hidden" value="2"><input id="audio_source" type="hidden" value="system"><input id="audio_device" type="hidden">
</section>

<section class="card"><div class="head"><div><h2>Работа программы</h2><p class="muted">Автозапуск и экранный индикатор</p></div></div>
<label class="check"><input id="launch_with_windows" type="checkbox">Запускать вместе с Windows</label>
<label class="check"><input id="prevent_sleep" type="checkbox">Не переводить компьютер в спящий режим во время трансляции</label>
<label class="check"><input id="keep_display_on" type="checkbox">Не выключать монитор во время трансляции</label>
<div class="sectionline"></div>
<label class="check"><input id="overlay_enabled" type="checkbox">Показывать надпись «Ведётся запись экрана»</label>
<div class="actions"><button id="placeOverlayButton" class="btn" onclick="placeOverlay()">Изменить положение</button><span class="muted" style="align-self:center">Надпись перемещается только после нажатия этой кнопки.</span></div>
<input id="overlay_x" type="hidden"><input id="overlay_y" type="hidden"><input id="overlay_text" type="hidden">
</section>

<section class="card">
<div class="head"><div><h2>Журнал работы</h2><p class="muted">Информация для диагностики подключения и трансляции</p></div></div>
<div class="actions"><button class="btn" onclick="toggleLog()">Показать журнал</button><button class="btn" onclick="downloadLogs()">Сохранить журнал в файл</button><button class="btn" onclick="openLogsFolder()">Открыть папку журналов</button></div>
<div id="log" class="log hidden" style="margin-top:10px"></div>
<input id="ffmpeg_path" type="hidden"><input id="mediamtx_path" type="hidden"><input id="restart_delay_s" type="hidden"><input id="audio_source" type="hidden"><input id="audio_device" type="hidden">
</section>

</main><aside class="sidebar"><div class="sidebar-sticky"><section class="card"><div class="head"><h2>Состояние</h2></div><div id="summary" class="summary muted">Загрузка…</div></section></div></aside></div>
</div>
<div class="bottom"><div class="bottomin"><div id="bottomInfo" class="recordstate">Поток остановлен</div><div class="bottomactions"><button id="saveAllButton" class="btn footer-save" onclick="saveAllSettings()">Сохранить настройки</button><button class="btn" onclick="restartStream()">Перезапустить поток</button><button class="btn stop" onclick="stopStream()">Остановить</button><button class="btn primary" onclick="startStream()">Запустить поток</button></div></div></div>
<script>
const numericIds=new Set(['local_rtsp_port','monitor_index','monitor_number','fps','bitrate_kbps','maxrate_kbps','bufsize_kbps','audio_bitrate_kbps','audio_sample_rate','audio_channels','overlay_x','overlay_y','restart_delay_s']);
const fieldIds=['resolution_profile','link','protocol','ffmpeg_path','mediamtx_path','local_rtsp_port','local_rtsp_path','monitor_index','monitor_number','quality_profile','fps','bitrate_kbps','maxrate_kbps','bufsize_kbps','encoder','preset','audio_quality','audio_source','audio_device','audio_bitrate_kbps','audio_sample_rate','audio_channels','overlay_text','overlay_x','overlay_y','restart_delay_s'];
let lastStatus={},currentConfig={},monitorItems=[];
async function api(path,opt={}){opt={...opt};const method=(opt.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD'){opt.headers={...(opt.headers||{}),'X-LinkVideo-Request':'1'}}const r=await fetch(path,opt);const type=r.headers.get('content-type')||'';const j=type.includes('json')?await r.json().catch(()=>({})):{};if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function notify(text,type='ok'){const e=document.getElementById('message');e.textContent=text;e.className='message show '+type;clearTimeout(window.msgTimer);window.msgTimer=setTimeout(()=>e.className='message',3600)}
function radioValue(name){const e=document.querySelector('input[name="'+name+'"]:checked');return e?e.value:''}
function setRadio(name,value){document.querySelectorAll('input[name="'+name+'"]').forEach(e=>e.checked=e.value===value)}
function getValue(id){const e=document.getElementById(id);if(!e)return null;return numericIds.has(id)?Number(e.value||0):e.value}
function collect(){const o={};fieldIds.forEach(id=>o[id]=getValue(id));o.output_mode=radioValue('output_mode')||'remote';o.capture_mode=radioValue('capture_mode')||'full';['cursor','privacy_protection','audio_enabled','launch_with_windows','prevent_sleep','keep_display_on','overlay_enabled'].forEach(id=>o[id]=document.getElementById(id).checked);return o}
async function persistSettings(restart,quiet=false){const button=document.getElementById('saveAllButton');try{if(button){button.disabled=true;button.classList.add('saving');button.textContent='Сохранение…'}const saved=await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(collect())});currentConfig=saved;applyConfig(saved);if(restart&&lastStatus.desired){api('/api/restart',{method:'POST'}).then(()=>status()).catch(e=>notify(e.message,'error'));if(!quiet)notify('Настройки сохранены. Трансляция перезапускается')}else if(!quiet)notify('Настройки сохранены');await status();return true}catch(e){notify(e.message,'error');return false}finally{if(button){button.disabled=false;button.classList.remove('saving');button.textContent='Сохранить настройки'}}}
async function saveAllSettings(){return persistSettings(true,false)}
function outputModeChanged(){const mode=radioValue('output_mode');document.getElementById('remotePanel').classList.toggle('hidden',mode!=='remote');document.getElementById('localPanel').classList.toggle('hidden',mode!=='local');document.getElementById('remoteMode').classList.toggle('active',mode==='remote');document.getElementById('localMode').classList.toggle('active',mode==='local');refreshLocalLinks()}
function captureChanged(){const mode=radioValue('capture_mode');document.querySelectorAll('.captureMode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));document.getElementById('monitorPanel').classList.toggle('hidden',mode!=='monitor')}
function audioChanged(){const on=document.getElementById('audio_enabled').checked;document.getElementById('audioSettings').style.opacity=on?'1':'.45';document.querySelectorAll('.audio-profile').forEach(x=>x.disabled=!on)}
function setAudioQuality(name){const rates={low:64,medium:128,high:192},v=rates[name]||128;document.getElementById('audio_quality').value=name;document.getElementById('audio_bitrate_kbps').value=v;document.querySelectorAll('.audio-profile').forEach(x=>x.classList.toggle('active',x.dataset.audioProfile===name))}
function setResolution(name){document.getElementById('resolution_profile').value=name;document.querySelectorAll('.resolution-profile').forEach(x=>x.classList.toggle('active',x.dataset.resolution===name))}
function setProfile(name){const rates={economy:256,fast:512,medium:1024},v=rates[name];document.getElementById('quality_profile').value=name;document.getElementById('bitrate_kbps').value=v;document.getElementById('maxrate_kbps').value=v;document.getElementById('bufsize_kbps').value=v*2;document.querySelectorAll('.profile[data-profile]').forEach(x=>x.classList.toggle('active',x.dataset.profile===name))}
function applyConfig(c){currentConfig=c;fieldIds.forEach(id=>{const e=document.getElementById(id);if(e&&c[id]!==undefined)e.value=c[id]??''});setRadio('output_mode',c.output_mode||'remote');setRadio('capture_mode',c.capture_mode==='monitor'?'monitor':'full');['cursor','privacy_protection','audio_enabled','launch_with_windows','prevent_sleep','keep_display_on','overlay_enabled'].forEach(id=>document.getElementById(id).checked=!!c[id]);document.querySelectorAll('.resolution-profile').forEach(x=>x.classList.toggle('active',x.dataset.resolution===(c.resolution_profile||'original')));document.querySelectorAll('.profile[data-profile]').forEach(x=>x.classList.toggle('active',x.dataset.profile===(c.quality_profile||'')));document.querySelectorAll('.audio-profile').forEach(x=>x.classList.toggle('active',x.dataset.audioProfile===(c.audio_quality||'medium')));outputModeChanged();captureChanged();audioChanged();renderMonitors()}
async function loadMonitors(){try{monitorItems=await api('/api/monitors');renderMonitors()}catch(e){monitorItems=[];renderMonitors()}}
function renderMonitors(){const box=document.getElementById('monitorGrid');if(!box)return;const selectedIndex=Number(document.getElementById('monitor_index').value||0),selectedNumber=Number(document.getElementById('monitor_number').value||0);box.innerHTML='';const items=[...monitorItems];if(!items.length){box.innerHTML='<div class="hint">Подключённые мониторы не найдены</div>';return}const minX=Math.min(...items.map(m=>m.x)),minY=Math.min(...items.map(m=>m.y)),maxX=Math.max(...items.map(m=>m.x+m.width)),maxY=Math.max(...items.map(m=>m.y+m.height));const totalW=Math.max(1,maxX-minX),totalH=Math.max(1,maxY-minY),pad=2,usable=96;items.forEach(m=>{const number=m.display_number||m.index+1;const selected=selectedNumber?number===selectedNumber:m.index===selectedIndex;const b=document.createElement('button');b.type='button';b.className='monitor-card'+(selected?' selected':'');b.onclick=()=>selectMonitor(m.index,number);b.style.left=(pad+(m.x-minX)/totalW*usable)+'%';b.style.top=(pad+(m.y-minY)/totalH*usable)+'%';b.style.width=Math.max(12,m.width/totalW*usable)+'%';b.style.height=Math.max(18,m.height/totalH*usable)+'%';const icon=document.createElement('span');icon.className='monitor-icon';icon.textContent=String(number);const meta=document.createElement('span');meta.className='monitor-meta';const title=m.model||('Монитор '+number);const details=m.width+'×'+m.height+(m.primary?' · основной':'');meta.innerHTML='<b>'+escapeHTML(title)+'</b><span>'+escapeHTML(details)+'</span>';b.append(icon,meta);box.appendChild(b)})}
function selectMonitor(index,number){document.getElementById('monitor_index').value=index;document.getElementById('monitor_number').value=number;renderMonitors()}
async function placeOverlay(){const b=document.getElementById('placeOverlayButton');try{if(b){b.disabled=true;b.textContent='Перемещение…'}notify('Перетащите надпись в нужное место и отпустите мышь');const p=await api('/api/place-overlay',{method:'POST'});document.getElementById('overlay_x').value=p.x;document.getElementById('overlay_y').value=p.y;notify('Положение надписи сохранено')}catch(e){notify(e.message,'error')}finally{if(b){b.disabled=false;b.textContent='Изменить положение'}}}
async function startStream(){if(!await persistSettings(false,true))return;try{await api('/api/start',{method:'POST'});notify('Трансляция запускается');await status()}catch(e){notify(e.message,'error')}}
async function stopStream(){try{await api('/api/stop',{method:'POST'});notify('Трансляция остановлена');await status()}catch(e){notify(e.message,'error')}}
async function restartStream(){try{await api('/api/restart',{method:'POST'});notify('Трансляция перезапускается');await status()}catch(e){notify(e.message,'error')}}
async function testConnection(){if(!await persistSettings(false,true))return;try{const x=await api('/api/test',{method:'POST'});notify('Сервер доступен: '+x.destination)}catch(e){notify(e.message,'error')}}
function toggleLog(){document.getElementById('log').classList.toggle('hidden')}
function downloadLogs(){window.location='/api/logs/download'}
async function openLogsFolder(){try{await api('/api/logs/open-folder',{method:'POST'});notify('Папка журналов открыта')}catch(e){notify(e.message,'error')}}
function applyLocalLinks(local,lan){const e=document.getElementById('localRTSPURL');if(e)e.textContent=lan||local||'—'}
async function refreshLocalLinks(){try{const x=await api('/api/local-links');applyLocalLinks(x.local,x.lan)}catch(e){}}
async function copyText(id){try{await navigator.clipboard.writeText(document.getElementById(id).textContent);notify('Ссылка скопирована')}catch(e){}}
function toggleLink(){const e=document.getElementById('link');e.type=e.type==='password'?'text':'password'}
function formatTime(iso){if(!iso)return '—';try{return new Date(iso).toLocaleTimeString()}catch(e){return iso}}
function formatDuration(iso){if(!iso)return '—';const started=new Date(iso).getTime();if(!Number.isFinite(started))return '—';let sec=Math.max(0,Math.floor((Date.now()-started)/1000));const d=Math.floor(sec/86400);sec%=86400;const h=Math.floor(sec/3600);sec%=3600;const m=Math.floor(sec/60);const ss=sec%60;const parts=[];if(d)parts.push(d+' д');if(h||d)parts.push(h+' ч');if(m||h||d)parts.push(m+' мин');if(!d&&!h)parts.push(ss+' сек');return parts.join(' ')}
function encoderName(name){return ({h264_qsv:'Intel Quick Sync',h264_nvenc:'NVIDIA NVENC',h264_amf:'AMD AMF',libx264:'Программный H.264'})[name]||name||'—'}
async function status(){try{const s=await api('/api/status');lastStatus=s;document.getElementById('version').textContent='Версия '+s.version;const text=s.running?'поток работает':(s.desired?'подключение…':'поток остановлен');document.getElementById('statusText').textContent=text;const dot=document.getElementById('statusDot');dot.className='dot '+(s.running?'ok':s.desired?'wait':s.last_error?'bad':'');document.getElementById('bottomInfo').textContent=s.running?(currentConfig.audio_enabled?'Изображение и звук передаются':'Изображение передаётся'):s.desired?'Выполняется подключение…':'Поток остановлен';let html='<div class="summary-row"><b>Состояние</b><span>'+escapeHTML(text)+'</span></div><div class="summary-row"><b>Источник</b><span>'+escapeHTML(s.capture_status||'—')+'</span></div>';if(s.video_encoder)html+='<div class="summary-row"><b>Кодировщик</b><span>'+escapeHTML(encoderName(s.video_encoder))+'</span></div>';if(s.running&&s.started_at)html+='<div class="summary-row"><b>Время работы</b><span>'+escapeHTML(formatDuration(s.started_at))+'</span></div>';html+='<div class="summary-row"><b>Переподключения</b><span>'+s.restarts+'</span></div>';if(s.last_restart_reason)html+='<div class="summary-row"><b>Последняя причина</b><span>'+escapeHTML(s.last_restart_reason)+'<br>'+formatTime(s.last_restart_at)+'</span></div>';document.getElementById('summary').innerHTML=html;document.getElementById('log').textContent=(s.recent_log||[]).join('\n')||'Журнал пуст';if(s.local_rtsp_url||s.local_rtsp_lan_url)applyLocalLinks(s.local_rtsp_url,s.local_rtsp_lan_url)}catch(e){}}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){const results=await Promise.all([api('/api/config'),api('/api/monitors').catch(()=>[])]);monitorItems=results[1];applyConfig(results[0]);document.querySelectorAll('input[name="output_mode"]').forEach(x=>x.onchange=outputModeChanged);document.querySelectorAll('input[name="capture_mode"]').forEach(x=>x.onchange=captureChanged);await status()}
load().catch(e=>notify(e.message,'error'));setInterval(status,2000);
</script>
</body></html>`
