package main

import (
	"context"
)

type secureFrameHandler func(frame []byte, active bool)

type secureDesktopBridge interface {
	Run(ctx context.Context, handler secureFrameHandler)
	SetSessionLocked(locked bool)
	Close() error
}

// secureFrameLooksBlank reports whether a BGRA frame is effectively a blank
// black surface. During Win+L some GPU/driver combinations briefly return an
// all-black DXGI frame after a valid Winlogon frame. Treating that transient as
// a new frame would overwrite the real lock screen and leave the stream black
// until the user presses a key.
func secureFrameLooksBlank(frame []byte) bool {
	pixels := len(frame) / 4
	if pixels == 0 {
		return true
	}

	// Sample at most about 8K pixels. The test is intentionally conservative:
	// only a nearly uniform, very dark image is considered invalid. A dark lock
	// screen with a clock, cursor or password controls remains a valid frame.
	stride := pixels / 8192
	if stride < 1 {
		stride = 1
	}

	var sampled, visible int
	maxChannel := byte(0)
	for pixel := 0; pixel < pixels; pixel += stride {
		i := pixel * 4
		b, g, r := frame[i], frame[i+1], frame[i+2]
		m := r
		if g > m {
			m = g
		}
		if b > m {
			m = b
		}
		if m > maxChannel {
			maxChannel = m
		}
		if m > 18 {
			visible++
		}
		sampled++
	}
	if sampled == 0 {
		return true
	}
	// Uniform near-black frames generated by a failed duplication surface have
	// no meaningful content. Require both a low maximum and almost no visible
	// samples to avoid rejecting legitimate dark wallpapers.
	return maxChannel <= 28 && visible*1000 <= sampled
}
