package main

const indexHTML = `<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>LinkVideo Monitor</title>
<link rel="icon" href="/favicon.ico" type="image/x-icon">
<style>
:root{--bg:#f4f5f7;--card:#fff;--line:#dfe3e8;--text:#20252b;--muted:#69727c;--dark:#414346;--orange:#ffad19;--orange2:#eb9600;--green:#168f4a;--red:#bd3737;--shadow:0 10px 28px rgba(30,39,48,.07)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px "Segoe UI",Arial,sans-serif}button,input,select{font:inherit}button{color:inherit}.hidden{display:none!important}
.top{height:68px;background:var(--dark);color:#fff;position:sticky;top:0;z-index:30}.topin{max-width:1260px;height:68px;margin:auto;padding:0 22px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:11px;font-size:22px;font-weight:720}.logo{width:31px;height:31px;position:relative}.logo:before,.logo:after{content:"";position:absolute;transform:rotate(45deg)}.logo:before{width:18px;height:18px;background:var(--orange);left:3px;top:8px}.logo:after{width:12px;height:12px;background:#c9cccf;left:17px;top:3px}.statusline{display:flex;align-items:center;gap:9px}.dot{width:10px;height:10px;border-radius:50%;background:#9ca2a8}.dot.ok{background:#31c66d;box-shadow:0 0 0 4px rgba(49,198,109,.15)}.dot.wait{background:#f3b330}.dot.bad{background:#ef6767}
.wrap{max-width:1260px;margin:24px auto 102px;padding:0 22px}.intro{display:flex;justify-content:space-between;align-items:flex-end;gap:16px;margin-bottom:16px}.intro h1{font-size:26px;margin:0}.muted{color:var(--muted);line-height:1.45}.grid{display:grid;grid-template-columns:minmax(0,1fr) 340px;gap:16px;align-items:start}.stack{display:flex;flex-direction:column;gap:16px}.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:19px;box-shadow:var(--shadow)}.head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:15px}.head h2{font-size:17px;margin:0}.head p{margin:3px 0 0}.row2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.row3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}label.field{display:block;color:#505a64;font-size:13px;margin:11px 0 6px}input[type=text],input[type=password],input[type=number],select{width:100%;min-height:40px;padding:9px 10px;border:1px solid #cfd5dc;border-radius:8px;background:#fff;outline:none}input:focus,select:focus{border-color:var(--orange2);box-shadow:0 0 0 3px rgba(235,150,0,.12)}input:disabled,select:disabled{background:#f0f2f4;color:#8b9299}
.modegrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.mode{display:block;border:1px solid var(--line);border-radius:11px;padding:13px;cursor:pointer;background:#fff}.mode.active{border-color:var(--orange2);background:#fff9ec;box-shadow:0 0 0 2px rgba(235,150,0,.12)}.mode input{display:none}.mode strong{display:block;margin-bottom:4px}.mode span{font-size:12px;color:var(--muted)}
.btn{border:1px solid #cdd3d9;background:#fff;border-radius:8px;padding:9px 12px;cursor:pointer;transition:.15s}.btn:hover:not(:disabled){background:#f5f6f7}.btn:disabled{opacity:.48;cursor:not-allowed}.btn.primary{background:var(--orange);border-color:var(--orange2);font-weight:700}.btn.stop{color:#a42d2d;background:#fff2f2;border-color:#e3b3b3}.btn.link{border:0;background:transparent;color:#4c6f9e;padding:3px 0;text-decoration:underline}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.linkline{display:flex;gap:8px}.linkline>*:first-child{flex:1}.check{display:flex;gap:9px;align-items:flex-start;margin:12px 0;cursor:pointer}.check input{margin-top:3px;accent-color:var(--orange2)}.hint{margin-top:10px;padding:10px 11px;border-radius:8px;background:#f7f8fa;color:var(--muted);font-size:12.5px;line-height:1.45}.hint.good{background:#edf8f1;color:#166b3b}.hint.bad{background:#fff0f0;color:#9e3030}.hint.warn{background:#fff7e6;color:#805400;border:1px solid #f2d28c}.sectionline{height:1px;background:#eceef1;margin:16px 0}
.profiles{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.profile{border:1px solid var(--line);border-radius:10px;padding:11px;text-align:left;background:#fff;cursor:pointer}.profile.active{border-color:var(--orange2);background:#fff9ec;box-shadow:0 0 0 2px rgba(235,150,0,.12)}.profile b{display:block}.profile small{color:var(--muted)}
.monitor-layout{position:relative;height:270px;margin-top:12px;border:1px solid var(--line);border-radius:12px;background:#eef1f4;overflow:hidden}.monitor-card{position:absolute;display:flex;align-items:center;justify-content:center;gap:8px;padding:8px;border:2px solid transparent;border-radius:11px;background:#fff;cursor:pointer;text-align:left;box-shadow:inset 0 0 0 1px var(--line)}.monitor-card.selected{border-color:var(--orange2);background:#fff9ec;box-shadow:0 0 0 2px rgba(235,150,0,.12)}.monitor-icon{width:38px;height:29px;border:2px solid #707983;border-radius:5px;display:grid;place-items:center;background:#eef1f4;color:#4c5660;font-weight:750;flex:0 0 auto}.monitor-meta{min-width:0}.monitor-meta b,.monitor-meta span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.monitor-meta span{color:var(--muted);font-size:12px;margin-top:3px}
.badge{display:inline-block;padding:4px 8px;border-radius:99px;background:#eceff2;color:#5c6570;font-size:12px}.summary{line-height:1.55}.summary-row{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px solid #eef0f2}.summary-row:last-child{border-bottom:0}.summary-row span{color:var(--muted);text-align:right}.sidebar-sticky{position:sticky;top:84px;display:flex;flex-direction:column;gap:12px}.log{white-space:pre-wrap;word-break:break-word;max-height:320px;overflow:auto;background:#171a1e;color:#d9dee3;border-radius:9px;padding:12px;font:12px Consolas,monospace}.smallvalue{padding:9px 10px;border:1px solid var(--line);border-radius:8px;background:#f7f8f9;word-break:break-all}
.message{position:fixed;right:22px;top:82px;z-index:70;max-width:460px;padding:12px 15px;border-radius:9px;background:#24292e;color:#fff;box-shadow:0 12px 35px rgba(0,0,0,.23);display:none}.message.show{display:block}.message.error{background:#a73535}
.bottom{position:fixed;left:0;right:0;bottom:0;background:rgba(255,255,255,.96);border-top:1px solid #d8dde2;backdrop-filter:blur(8px);z-index:35}.bottomin{max-width:1260px;margin:auto;padding:11px 22px;display:flex;align-items:center;justify-content:space-between;gap:14px}.bottomactions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.recordstate{font-weight:650}.save-dirty{background:#fff9ec;border-color:var(--orange2);font-weight:700}
.modalback{position:fixed;inset:0;background:rgba(20,24,29,.5);z-index:100;display:flex;align-items:center;justify-content:center;padding:18px}.modal{width:min(470px,100%);max-height:85vh;overflow:auto;background:#fff;border-radius:14px;box-shadow:0 24px 70px rgba(0,0,0,.28);padding:20px}.modal h3{margin:0 0 7px;font-size:19px}.modalactions{display:flex;justify-content:flex-end;gap:8px;margin-top:17px}.historyitem{padding:11px 0;border-bottom:1px solid #eceff2}.historyitem:last-child{border-bottom:0}.historytime{font-size:12px;color:var(--muted);margin-top:4px}.device-state{font-size:12px;color:var(--muted);margin-top:6px}.mic-level{height:8px;background:#e7eaee;border-radius:99px;overflow:hidden;margin-top:8px}.mic-level>i{display:block;height:100%;width:0;background:linear-gradient(90deg,#43b56f,#ffad19);transition:width .12s}.hotkey{cursor:pointer;background:#fff}.mic-runtime{display:flex;align-items:center;gap:8px;margin-top:10px}.mic-runtime .dot{flex:0 0 auto}
@media(max-width:920px){.grid{grid-template-columns:1fr}.sidebar-sticky{position:static}.profiles{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){.topin{padding:0 12px}.statusline{display:none}.row2,.row3,.modegrid,.profiles{grid-template-columns:1fr}.monitor-layout{height:220px}.intro{align-items:flex-start;flex-direction:column}.bottomin{align-items:flex-start}.bottomactions{justify-content:flex-end}}
</style>
</head>
<body>
<div class="top"><div class="topin"><div class="brand"><div class="logo"></div><div>LinkVideo Monitor</div></div><div class="statusline"><span id="statusDot" class="dot"></span><span id="statusText">загрузка…</span></div></div></div>
<div id="message" class="message"></div>
<div class="wrap">
<div class="intro"><h1>Трансляция экрана</h1><span id="version" class="badge"></span></div>
<div class="grid"><main class="stack">

<section class="card"><div class="head"><div><h2>Подключение</h2><p class="muted">Куда отправлять поток</p></div></div>
<div class="modegrid">
<label class="mode" id="remoteMode"><input type="radio" name="output_mode" value="remote"><strong>Сервер LinkVideo</strong><span>Передача трансляции в облако.</span></label>
<label class="mode" id="localMode"><input type="radio" name="output_mode" value="local"><strong>Локальная RTSP-трансляция</strong><span>Ссылка для LinkVideo Server.</span></label>
</div>
<div id="remotePanel"><label class="field">Ссылка подключения</label><div class="linkline"><input id="link" type="password" placeholder="linkvideomonitor:…"><button class="btn" type="button" onclick="toggleLink()">Показать</button></div><div class="row2"><div><label class="field">Протокол передачи</label><select id="protocol"><option value="rtsp">RTSP</option><option value="rtmp">RTMP</option></select></div><div><label class="field">Проверка</label><button class="btn" type="button" style="width:100%" onclick="testConnection()">Проверить сервер</button></div></div></div>
<div id="localPanel" class="hidden"><label class="field">Локальный RTSP-порт</label><input id="local_rtsp_port" type="number" min="1" max="65535"><div id="portStatus" class="hint hidden"></div><div class="hint warn">Закрепите IP-адрес этого компьютера в DHCP-настройках роутера. При смене IP локальная RTSP-ссылка перестанет быть доступна.</div><input id="local_rtsp_path" type="hidden" value="screen"><label class="field">RTSP-ссылка</label><div class="linkline"><div id="localRTSPURL" class="smallvalue">—</div><button class="btn" type="button" onclick="copyText('localRTSPURL','Ссылка скопирована')">Копировать</button></div></div>
</section>

<section class="card"><div class="head"><div><h2>Источник изображения</h2><p class="muted">Что будет видно в трансляции</p></div></div>
<div class="modegrid">
<label class="mode captureMode" data-mode="full"><input type="radio" name="capture_mode" value="full"><strong>Все экраны</strong><span>Весь рабочий стол со всеми мониторами.</span></label>
<label class="mode captureMode" data-mode="monitor"><input type="radio" name="capture_mode" value="monitor"><strong>Выбранный монитор</strong><span>Изображение только с одного экрана.</span></label>
</div>
<div id="monitorPanel" class="hidden"><div id="monitorGrid" class="monitor-layout"></div><div class="hint">Мониторы расположены так же, как в параметрах дисплея Windows.</div><input id="monitor_index" type="hidden"><input id="monitor_number" type="hidden"></div>
<label class="check"><input id="cursor" type="checkbox">Показывать курсор мыши</label>
<label class="check"><input id="privacy_protection" type="checkbox">Скрывать пароли, PIN и чувствительные данные пикселизацией</label>
<div class="hint">Чувствительные поля закрываются до кодирования и отправки на сервер.</div>
</section>

<section class="card"><div class="head"><div><h2>Качество изображения</h2><p class="muted">Разрешение, битрейт, плавность и кодек</p></div></div>
<label class="field">Разрешение трансляции</label><div class="profiles">
<button type="button" class="profile resolution-profile" data-resolution="original" onclick="setResolution('original')"><b>Исходное</b><small>Разрешение монитора</small></button>
<button type="button" class="profile resolution-profile" data-resolution="full_hd" onclick="setResolution('full_hd')"><b>Full HD</b><small>1920×1080</small></button>
<button type="button" class="profile resolution-profile" data-resolution="hd" onclick="setResolution('hd')"><b>HD</b><small>1280×720</small></button>
</div><input id="resolution_profile" type="hidden">
<label class="field">Качество передачи</label><div class="profiles">
<button type="button" class="profile" data-profile="economy" onclick="setProfile('economy')"><b>Экономный</b><small>256 Кбит/с</small></button>
<button type="button" class="profile" data-profile="fast" onclick="setProfile('fast')"><b>Быстрый</b><small>512 Кбит/с</small></button>
<button type="button" class="profile" data-profile="medium" onclick="setProfile('medium')"><b>Стандартный</b><small>1024 Кбит/с</small></button>
</div><input id="quality_profile" type="hidden">
<div class="row3"><div><label class="field">Частота кадров</label><select id="fps"><option value="15">15 кадров/с</option><option value="25">25 кадров/с</option><option value="30">30 кадров/с</option></select></div><div><label class="field">Формат видео</label><select id="codec" onchange="codecChanged()"><option value="h264">H.264</option><option value="h265">H.265</option></select></div><div><label class="field">Кодировщик</label><select id="encoder"><option value="libx264">Программный H.264</option></select></div></div>
<input id="bitrate_kbps" type="hidden"><input id="maxrate_kbps" type="hidden"><input id="bufsize_kbps" type="hidden"><input id="preset" type="hidden">
</section>

<section class="card" id="audioCard"><div class="head"><div><h2>Звук</h2><p class="muted">Выберите источники звука для трансляции</p></div></div>
<label class="check"><input id="audio_enabled" type="checkbox" onchange="audioChanged()">Передавать звук компьютера</label>
<label class="check"><input id="microphone_enabled" type="checkbox" onchange="microphoneChanged()">Передавать звук микрофона</label>
<div id="microphoneSettings"><label class="field">Устройство ввода</label><select id="microphone_device"><option value="">Выберите микрофон</option></select><div id="microphoneStatus" class="device-state"></div>
<label class="field">Режим использования</label><div class="profiles">
<button type="button" class="profile microphone-mode" data-microphone-mode="always" onclick="setMicrophoneMode('always')"><b>Постоянно</b><small>Микрофон передаётся всегда</small></button>
<button type="button" class="profile microphone-mode" data-microphone-mode="voice" onclick="setMicrophoneMode('voice')"><b>По голосу</b><small>Включается при разговоре</small></button>
<button type="button" class="profile microphone-mode" data-microphone-mode="push_to_talk" onclick="setMicrophoneMode('push_to_talk')"><b>По клавише</b><small>Работает при удержании</small></button></div>
<input id="microphone_mode" type="hidden">
<div id="voiceSettings"><label class="field">Чувствительность активации голосом</label><input id="microphone_voice_db" type="range" min="-60" max="-20" step="1"><div class="device-state">Чем правее, тем громче должен быть голос.</div></div>
<div id="pttSettings"><label class="field">Клавиша разговора</label><input id="microphone_ptt_hotkey" class="hotkey" type="text" readonly onclick="captureHotkey(this)" title="Нажмите и затем задайте сочетание"></div>
<label class="field">Включить / выключить микрофон</label><input id="microphone_toggle_hotkey" class="hotkey" type="text" readonly onclick="captureHotkey(this)" title="Нажмите и затем задайте сочетание">
<div class="hint">Горячие клавиши работают глобально, даже когда окно программы закрыто.</div>
<div class="mic-runtime"><span id="micRuntimeDot" class="dot"></span><span id="micRuntimeText" class="device-state">Микрофон выключен</span></div><div class="mic-level"><i id="micLevelBar"></i></div></div>
<div id="audioSettings"><label class="field">Качество общей аудиодорожки</label><div class="profiles">
<button type="button" class="profile audio-profile" data-audio-profile="low" onclick="setAudioQuality('low')"><b>Базовое</b><small>64 Кбит/с</small></button>
<button type="button" class="profile audio-profile" data-audio-profile="medium" onclick="setAudioQuality('medium')"><b>Оптимальное</b><small>128 Кбит/с</small></button>
<button type="button" class="profile audio-profile" data-audio-profile="high" onclick="setAudioQuality('high')"><b>Высокое</b><small>192 Кбит/с</small></button>
</div></div>
<input id="audio_quality" type="hidden"><input id="audio_bitrate_kbps" type="hidden"><input id="audio_sample_rate" type="hidden" value="48000"><input id="audio_channels" type="hidden" value="2"><input id="audio_advance_ms" type="hidden" value="800"><input id="audio_source" type="hidden" value="system"><input id="audio_device" type="hidden">
</section>

<section class="card"><div class="head"><div><h2>Работа программы</h2><p class="muted">Автозапуск и экранный индикатор</p></div></div>
<label class="check"><input id="launch_with_windows" type="checkbox">Запускать вместе с Windows</label>
<label class="check"><input id="prevent_sleep" type="checkbox">Не переводить компьютер в спящий режим во время трансляции</label>
<label class="check"><input id="keep_display_on" type="checkbox">Не выключать монитор во время трансляции</label>
<div class="sectionline"></div>
<label class="check"><input id="overlay_enabled" type="checkbox">Показывать надпись «Ведётся запись экрана»</label>
<div class="actions"><button id="placeOverlayButton" class="btn" type="button" onclick="placeOverlay()">Изменить положение</button></div><div class="hint">Для изменения положения зажмите надпись и перетащите её мышью.</div>
<input id="overlay_x" type="hidden"><input id="overlay_y" type="hidden"><input id="overlay_text" type="hidden">
</section>

<section class="card"><div class="head"><div><h2>Журнал работы</h2><p class="muted">Диагностика подключения и трансляции</p></div></div>
<div class="actions"><button class="btn" type="button" onclick="toggleLog()">Показать журнал</button><button class="btn" type="button" onclick="copyLogs()">Скопировать журнал</button><button class="btn" type="button" onclick="openLogsFolder()">Открыть папку журналов</button></div>
<div id="log" class="log hidden" style="margin-top:10px"></div>
<input id="ffmpeg_path" type="hidden"><input id="mediamtx_path" type="hidden"><input id="restart_delay_s" type="hidden">
</section>

</main><aside><div class="sidebar-sticky"><section class="card"><div class="head"><h2>Состояние</h2></div><div id="summary" class="summary muted">Загрузка…</div><div class="sectionline"></div><button id="checkUpdatesButton" class="btn" style="width:100%" type="button" onclick="checkUpdates()">Проверить обновления</button></section></div></aside></div>
</div>

<div class="bottom"><div class="bottomin"><div id="bottomInfo" class="recordstate">Поток остановлен</div><div class="bottomactions"><button id="saveAllButton" class="btn" type="button" disabled onclick="saveAllSettings()">Сохранить настройки</button><button id="restartStreamButton" class="btn" type="button" onclick="restartStream()">Перезапустить поток</button><button id="stopStreamButton" class="btn stop" type="button" onclick="stopStream()">Остановить</button><button id="startStreamButton" class="btn primary" type="button" onclick="startStream()">Запустить поток</button></div></div></div>

<div id="adminModal" class="modalback hidden"><div class="modal"><h3 id="adminTitle">Пароль администратора</h3><p id="adminText" class="muted"></p><label class="field" id="passwordLabel">Пароль</label><input id="adminPassword" type="password" autocomplete="current-password"><div id="confirmWrap" class="hidden"><label class="field">Повторите пароль</label><input id="adminConfirm" type="password" autocomplete="new-password"></div><div id="adminError" class="hint bad hidden"></div><div class="modalactions"><button class="btn" type="button" onclick="closeAdminModal(false)">Отмена</button><button class="btn primary" type="button" onclick="closeAdminModal(true)">Продолжить</button></div></div></div>
<div id="historyModal" class="modalback hidden"><div class="modal"><h3>История переподключений</h3><p class="muted">Время и причина каждого автоматического переподключения.</p><div id="historyList"></div><div class="modalactions"><button class="btn primary" type="button" onclick="closeHistory()">Закрыть</button></div></div></div>
<div id="localIPModal" class="modalback hidden"><div class="modal"><h3>Закрепите IP-адрес компьютера</h3><p class="muted">Для стабильной локальной RTSP-трансляции закрепите текущий IP-адрес этого компьютера в DHCP-настройках роутера. Если роутер выдаст компьютеру другой адрес, сохранённая RTSP-ссылка станет недоступна.</p><div class="modalactions"><button class="btn primary" type="button" onclick="closeLocalIPNotice()">Понятно</button></div></div></div>

<script>
const numericIds=new Set(['local_rtsp_port','monitor_index','monitor_number','fps','bitrate_kbps','maxrate_kbps','bufsize_kbps','audio_bitrate_kbps','audio_sample_rate','audio_channels','audio_advance_ms','microphone_voice_db','overlay_x','overlay_y','restart_delay_s']);
const fieldIds=['resolution_profile','link','protocol','ffmpeg_path','mediamtx_path','local_rtsp_port','local_rtsp_path','monitor_index','monitor_number','quality_profile','fps','bitrate_kbps','maxrate_kbps','bufsize_kbps','codec','encoder','preset','audio_quality','audio_source','audio_device','microphone_device','microphone_mode','microphone_voice_db','microphone_ptt_hotkey','microphone_toggle_hotkey','audio_bitrate_kbps','audio_sample_rate','audio_channels','audio_advance_ms','overlay_text','overlay_x','overlay_y','restart_delay_s'];
const checkIds=['cursor','privacy_protection','audio_enabled','microphone_enabled','launch_with_windows','prevent_sleep','keep_display_on','overlay_enabled'];
let lastStatus={},currentConfig={},monitorItems=[],encoderCapabilities=[],baseline='',baselineConfig={},adminToken='',adminResolve=null,audioDevicesLoaded=false,localIPNoticeShown=false;
async function api(path,opt={}){opt={...opt};const method=(opt.method||'GET').toUpperCase();opt.headers={...(opt.headers||{})};if(method!=='GET'&&method!=='HEAD')opt.headers['X-LinkVideo-Request']='1';if(adminToken)opt.headers['X-LinkVideo-Admin-Token']=adminToken;const r=await fetch(path,opt);const type=r.headers.get('content-type')||'';const j=type.includes('json')?await r.json().catch(()=>({})):{};if(!r.ok)throw Error(j.error||('HTTP '+r.status));return j}
function notify(text,type='ok'){const e=document.getElementById('message');e.textContent=text;e.className='message show '+type;clearTimeout(window.msgTimer);window.msgTimer=setTimeout(()=>e.className='message',4200)}
function radioValue(name){const e=document.querySelector('input[name="'+name+'"]:checked');return e?e.value:''}
function setRadio(name,value){document.querySelectorAll('input[name="'+name+'"]').forEach(e=>e.checked=e.value===value)}
function getValue(id){const e=document.getElementById(id);if(!e)return null;return numericIds.has(id)?Number(e.value||0):e.value}
function collect(){const o={};fieldIds.forEach(id=>o[id]=getValue(id));o.output_mode=radioValue('output_mode')||'remote';o.capture_mode=radioValue('capture_mode')||'full';checkIds.forEach(id=>o[id]=document.getElementById(id).checked);return o}
function setBaseline(){baselineConfig=collect();baseline=JSON.stringify(baselineConfig)}
function updateDirty(){if(!baseline)return;const dirty=JSON.stringify(collect())!==baseline;const b=document.getElementById('saveAllButton');b.disabled=!dirty;b.classList.toggle('save-dirty',dirty)}
function hasProtectedChanges(){const c=collect(),b=baselineConfig||{};return c.fps!==b.fps||c.bitrate_kbps!==b.bitrate_kbps||c.maxrate_kbps!==b.maxrate_kbps||c.bufsize_kbps!==b.bufsize_kbps||c.quality_profile!==b.quality_profile||c.launch_with_windows!==b.launch_with_windows||(b.overlay_enabled===true&&c.overlay_enabled===false)}
function hasStreamChanges(){const c=collect(),b=baselineConfig||{},keys=['privacy_protection','resolution_profile','link','output_mode','protocol','ffmpeg_path','mediamtx_path','local_rtsp_port','local_rtsp_path','capture_mode','monitor_index','monitor_number','quality_profile','fps','bitrate_kbps','maxrate_kbps','bufsize_kbps','codec','encoder','preset','cursor','audio_enabled','microphone_enabled','microphone_device','microphone_mode','microphone_voice_db','microphone_ptt_hotkey','microphone_toggle_hotkey','audio_quality','audio_source','audio_device','audio_bitrate_kbps','audio_sample_rate','audio_channels','audio_advance_ms'];return keys.some(k=>c[k]!==b[k])}
function bindDirtyTracking(){document.querySelectorAll('input,select').forEach(e=>{e.addEventListener('change',updateDirty);if(e.type==='text'||e.type==='password'||e.type==='number')e.addEventListener('input',updateDirty)})}
async function requestAdminToken(action){const st=await api('/api/auth/status');if(!st.configured)throw Error('Встроенный пароль администратора не настроен в этой сборке');const values=await showAdminModal(action);const x=await api('/api/auth/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:values.password})});return x.token}
async function withAdmin(action,fn){try{adminToken=await requestAdminToken(action);return await fn()}catch(e){if(e&&e.message!=='cancelled')notify(e.message,'error');return false}finally{adminToken=''}}
function adminActionText(action){if(action==='сохранение защищённых настроек')return 'Изменение настроек видео, автозапуска Windows и отключение индикатора разрешено только специалистам LinkVideo.';if(action==='запуск трансляции'||action==='остановка трансляции'||action==='перезапуск трансляции')return 'Управление трансляцией разрешено только специалистам LinkVideo.';return 'Это действие разрешено только специалистам LinkVideo.'}
function showAdminModal(action){return new Promise((resolve,reject)=>{adminResolve={resolve,reject};document.getElementById('adminTitle').textContent='Введите пароль администратора';document.getElementById('adminText').textContent=adminActionText(action);document.getElementById('passwordLabel').textContent='Пароль';document.getElementById('confirmWrap').classList.add('hidden');document.getElementById('adminPassword').value='';document.getElementById('adminConfirm').value='';document.getElementById('adminError').classList.add('hidden');document.getElementById('adminModal').classList.remove('hidden');setTimeout(()=>document.getElementById('adminPassword').focus(),50)})}
function closeAdminModal(ok){if(!adminResolve)return;const passwordInput=document.getElementById('adminPassword'),confirmInput=document.getElementById('adminConfirm');if(!ok){document.getElementById('adminModal').classList.add('hidden');passwordInput.value='';confirmInput.value='';adminResolve.reject(Error('cancelled'));adminResolve=null;return}const password=passwordInput.value;if(!password){showAdminError('Введите пароль');return}document.getElementById('adminModal').classList.add('hidden');passwordInput.value='';confirmInput.value='';adminResolve.resolve({password});adminResolve=null}
function showAdminError(text){const e=document.getElementById('adminError');e.textContent=text;e.classList.remove('hidden')}
document.addEventListener('keydown',e=>{if(hotkeyCaptureTarget){e.preventDefault();if(e.key==='Escape'){hotkeyCaptureTarget.value=hotkeyCaptureTarget.dataset.old||'';hotkeyCaptureTarget=null;return}const name=hotkeyName(e);if(name){hotkeyCaptureTarget.value=name;hotkeyCaptureTarget=null;updateDirty()}return}if(e.key==='Enter'&&!document.getElementById('adminModal').classList.contains('hidden'))closeAdminModal(true);if(e.key==='Escape'&&!document.getElementById('adminModal').classList.contains('hidden'))closeAdminModal(false)});
async function persistSettings(restart,quiet=false){const b=document.getElementById('saveAllButton'),willRestart=restart&&lastStatus.desired&&hasStreamChanges();try{b.disabled=true;b.textContent='Сохранение…';const saved=await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(collect())});applyConfig(saved);if(willRestart&&!quiet)notify('Настройки сохранены. Источник трансляции обновляется');else if(!quiet)notify('Настройки сохранены');await status();return true}catch(e){notify(e.message,'error');return false}finally{b.textContent='Сохранить настройки';updateDirty()}}
function restoreProtectedFields(){const b=baselineConfig||{};['fps','bitrate_kbps','maxrate_kbps','bufsize_kbps','quality_profile','launch_with_windows','overlay_enabled'].forEach(id=>{const e=document.getElementById(id);if(!e||b[id]===undefined)return;if(e.type==='checkbox')e.checked=!!b[id];else e.value=b[id]??''});document.querySelectorAll('.profile[data-profile]').forEach(x=>x.classList.toggle('active',x.dataset.profile===(b.quality_profile||'')));updateDirty()}
async function saveAllSettings(){if(hasProtectedChanges()){const ok=await withAdmin('сохранение защищённых настроек',()=>persistSettings(true,false));if(!ok)restoreProtectedFields();return ok}return persistSettings(true,false)}
function outputModeChanged(){const mode=radioValue('output_mode');document.getElementById('remotePanel').classList.toggle('hidden',mode!=='remote');document.getElementById('localPanel').classList.toggle('hidden',mode!=='local');document.getElementById('remoteMode').classList.toggle('active',mode==='remote');document.getElementById('localMode').classList.toggle('active',mode==='local');refreshLocalLinks();if(mode==='local'){checkLocalPort(false);if(!localIPNoticeShown){localIPNoticeShown=true;showLocalIPNotice()}}updateDirty()}
function captureChanged(){const mode=radioValue('capture_mode');document.querySelectorAll('.captureMode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));document.getElementById('monitorPanel').classList.toggle('hidden',mode!=='monitor');updateDirty()}
function audioChanged(){const on=document.getElementById('audio_enabled').checked||document.getElementById('microphone_enabled').checked;document.getElementById('audioSettings').style.opacity=on?'1':'.45';document.querySelectorAll('.audio-profile').forEach(x=>x.disabled=!on);updateDirty()}
function microphoneChanged(){const on=document.getElementById('microphone_enabled').checked,box=document.getElementById('microphoneSettings');box.style.opacity=on?'1':'.45';box.querySelectorAll('input,select,button').forEach(x=>x.disabled=!on);if(on)loadAudioDevices();microphoneModeChanged();audioChanged();updateDirty()}
function setMicrophoneMode(mode){document.getElementById('microphone_mode').value=mode;microphoneModeChanged();updateDirty()}
function microphoneModeChanged(){const mode=document.getElementById('microphone_mode').value||'always';document.querySelectorAll('.microphone-mode').forEach(x=>x.classList.toggle('active',x.dataset.microphoneMode===mode));document.getElementById('voiceSettings').classList.toggle('hidden',mode!=='voice');document.getElementById('pttSettings').classList.toggle('hidden',mode!=='push_to_talk')}
let hotkeyCaptureTarget=null;function captureHotkey(el){hotkeyCaptureTarget=el;el.dataset.old=el.value;el.value='Нажмите сочетание…';el.focus()}
function hotkeyName(e){const p=[];if(e.ctrlKey)p.push('Ctrl');if(e.altKey)p.push('Alt');if(e.shiftKey)p.push('Shift');if(e.metaKey)p.push('Win');if(['Control','Alt','Shift','Meta'].includes(e.key))return '';let k=e.code||e.key;if(k.startsWith('Key'))k=k.slice(3);else if(k.startsWith('Digit'))k=k.slice(5);else if(k==='Space')k='Space';else if(/^F\d+$/.test(k)){}else{k=e.key;if(k===' ')k='Space';else if(k.length===1)k=k.toUpperCase()}p.push(k);return p.join('+')}
function setAudioQuality(name){const rates={low:64,medium:128,high:192},v=rates[name]||128;document.getElementById('audio_quality').value=name;document.getElementById('audio_bitrate_kbps').value=v;document.querySelectorAll('.audio-profile').forEach(x=>x.classList.toggle('active',x.dataset.audioProfile===name));updateDirty()}
function setResolution(name){document.getElementById('resolution_profile').value=name;document.querySelectorAll('.resolution-profile').forEach(x=>x.classList.toggle('active',x.dataset.resolution===name));updateDirty()}
function setProfile(name){const rates={economy:256,fast:512,medium:1024},v=rates[name];document.getElementById('quality_profile').value=name;document.getElementById('bitrate_kbps').value=v;document.getElementById('maxrate_kbps').value=v;document.getElementById('bufsize_kbps').value=v*2;document.querySelectorAll('.profile[data-profile]').forEach(x=>x.classList.toggle('active',x.dataset.profile===name));updateDirty()}
function applyConfig(c){currentConfig=c;fieldIds.forEach(id=>{const e=document.getElementById(id);if(e&&c[id]!==undefined)e.value=c[id]??''});setRadio('output_mode',c.output_mode||'remote');setRadio('capture_mode',c.capture_mode==='monitor'?'monitor':'full');checkIds.forEach(id=>document.getElementById(id).checked=!!c[id]);document.querySelectorAll('.resolution-profile').forEach(x=>x.classList.toggle('active',x.dataset.resolution===(c.resolution_profile||'original')));document.querySelectorAll('.profile[data-profile]').forEach(x=>x.classList.toggle('active',x.dataset.profile===(c.quality_profile||'')));document.querySelectorAll('.audio-profile').forEach(x=>x.classList.toggle('active',x.dataset.audioProfile===(c.audio_quality||'medium')));outputModeChanged();captureChanged();audioChanged();microphoneChanged();renderMonitors();renderEncoderOptions(c.codec||'h264',c.encoder||'libx264');setBaseline();updateDirty()}
async function loadMonitors(){try{monitorItems=await api('/api/monitors');renderMonitors()}catch(e){monitorItems=[];renderMonitors()}}
function renderMonitors(){const box=document.getElementById('monitorGrid');if(!box)return;const selectedIndex=Number(document.getElementById('monitor_index').value||0),selectedNumber=Number(document.getElementById('monitor_number').value||0);box.innerHTML='';const items=[...monitorItems];if(!items.length){box.innerHTML='<div class="hint">Подключённые мониторы не найдены</div>';return}const minX=Math.min(...items.map(m=>m.x)),minY=Math.min(...items.map(m=>m.y)),maxX=Math.max(...items.map(m=>m.x+m.width)),maxY=Math.max(...items.map(m=>m.y+m.height));const totalW=Math.max(1,maxX-minX),totalH=Math.max(1,maxY-minY),pad=2,usable=96;items.forEach(m=>{const number=m.display_number||m.index+1;const selected=selectedNumber?number===selectedNumber:m.index===selectedIndex;const b=document.createElement('button');b.type='button';b.className='monitor-card'+(selected?' selected':'');b.onclick=()=>selectMonitor(m.index,number);b.style.left=(pad+(m.x-minX)/totalW*usable)+'%';b.style.top=(pad+(m.y-minY)/totalH*usable)+'%';b.style.width=Math.max(12,m.width/totalW*usable)+'%';b.style.height=Math.max(18,m.height/totalH*usable)+'%';const icon=document.createElement('span');icon.className='monitor-icon';icon.textContent=String(number);const meta=document.createElement('span');meta.className='monitor-meta';meta.innerHTML='<b>'+escapeHTML(m.model||('Монитор '+number))+'</b><span>'+escapeHTML(m.width+'×'+m.height+(m.primary?' · основной':''))+'</span>';b.append(icon,meta);box.appendChild(b)})}
function selectMonitor(index,number){document.getElementById('monitor_index').value=index;document.getElementById('monitor_number').value=number;renderMonitors();updateDirty()}
async function loadEncoderCapabilities(){try{encoderCapabilities=await api('/api/encoder-capabilities');const codecs=new Set(encoderCapabilities.filter(x=>x.available).map(x=>x.codec));const codec=document.getElementById('codec'),wanted=currentConfig.codec||codec.value||'h264';codec.innerHTML='';if(codecs.has('h264'))codec.add(new Option('H.264','h264'));if(codecs.has('h265'))codec.add(new Option('H.265','h265'));if(!codec.options.length)codec.add(new Option('H.264','h264'));codec.value=codecs.has(wanted)?wanted:codec.options[0].value;renderEncoderOptions(codec.value,currentConfig.encoder);setBaseline();updateDirty()}catch(e){notify('Не удалось проверить доступные кодировщики: '+e.message,'error')}}
function renderEncoderOptions(codec,wanted){const select=document.getElementById('encoder');const options=encoderCapabilities.filter(x=>x.available&&x.codec===codec);select.innerHTML='';if(!options.length){const fallback=codec==='h265'?'libx265':'libx264';select.add(new Option(codec==='h265'?'Программный H.265':'Программный H.264',fallback));select.value=fallback;return}options.forEach(x=>select.add(new Option(x.label,x.name)));select.value=options.some(x=>x.name===wanted)?wanted:options[0].name}
function codecChanged(){const codec=document.getElementById('codec').value;renderEncoderOptions(codec,'');updateDirty()}
async function loadAudioDevices(){if(audioDevicesLoaded)return;const status=document.getElementById('microphoneStatus');status.textContent='Получаем список устройств…';try{const devices=await api('/api/audio-devices');const select=document.getElementById('microphone_device'),wanted=currentConfig.microphone_device||select.value;select.innerHTML='<option value="">Выберите микрофон</option>';devices.forEach(name=>select.add(new Option(name,name)));if(devices.includes(wanted))select.value=wanted;status.textContent=devices.length?'Найдено устройств: '+devices.length:'Устройства ввода не найдены';audioDevicesLoaded=true;setBaseline();updateDirty()}catch(e){status.textContent=e.message;status.style.color='#9e3030'}}
async function checkLocalPort(showError=true){const e=document.getElementById('portStatus'),port=Number(document.getElementById('local_rtsp_port').value||0);try{await api('/api/check-port',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({port})});e.textContent='';e.className='hint hidden';return true}catch(err){e.textContent=err.message;e.className='hint bad';if(showError)notify(err.message,'error');return false}}
async function placeOverlay(){const b=document.getElementById('placeOverlayButton');try{b.disabled=true;b.textContent='Перемещение…';notify('Перетащите надпись и отпустите мышь');const p=await api('/api/place-overlay',{method:'POST'});document.getElementById('overlay_x').value=p.x;document.getElementById('overlay_y').value=p.y;setBaseline();updateDirty();notify('Положение надписи сохранено')}catch(e){notify(e.message,'error');return false}finally{b.disabled=false;b.textContent='Изменить положение'}return true}
async function startStream(){if(JSON.stringify(collect())!==baseline){if(hasProtectedChanges()){restoreProtectedFields();notify('Защищённые изменения не применены. Поток запускается с сохранёнными параметрами.')}if(JSON.stringify(collect())!==baseline&&!(await persistSettings(false,true)))return false}try{await api('/api/start',{method:'POST'});notify('Трансляция запускается');await status();return true}catch(e){notify(e.message,'error');return false}}
async function stopStream(){return withAdmin('остановка трансляции',async()=>{await api('/api/stop',{method:'POST'});notify('Трансляция остановлена');await status();return true})}
async function restartStream(){try{await api('/api/restart',{method:'POST'});notify('Трансляция перезапускается');await status();return true}catch(e){notify(e.message,'error');return false}}
async function testConnection(){try{const x=await api('/api/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(collect())});const server=x.server||x.destination||'указанный';notify('Сервер '+server+' доступен')}catch(e){notify(e.message,'error')}}
async function checkUpdates(){const b=document.getElementById('checkUpdatesButton');try{b.disabled=true;b.textContent='Проверка…';const x=await api('/api/check-updates',{method:'POST'});if(x.available){notify('Доступна версия '+x.latest_version);if(x.download_url&&confirm('Доступна версия '+x.latest_version+'. Открыть страницу загрузки?'))window.open(x.download_url,'_blank','noopener')}else notify('Установлена последняя версия')}catch(e){notify(e.message,'error')}finally{b.disabled=false;b.textContent='Проверить обновления'}}
function toggleLog(){document.getElementById('log').classList.toggle('hidden')}
async function copyLogs(){try{const r=await fetch('/api/logs/text');if(!r.ok)throw Error('Не удалось получить журнал');await navigator.clipboard.writeText(await r.text());notify('Журнал скопирован в буфер обмена')}catch(e){notify(e.message,'error')}}
async function openLogsFolder(){try{await api('/api/logs/open-folder',{method:'POST'});notify('Папка журналов открыта')}catch(e){notify(e.message,'error')}}
function applyLocalLinks(local,lan){document.getElementById('localRTSPURL').textContent=lan||local||'—'}
async function refreshLocalLinks(){try{const x=await api('/api/local-links');applyLocalLinks(x.local,x.lan)}catch(e){}}
async function copyText(id,message){try{await navigator.clipboard.writeText(document.getElementById(id).textContent);notify(message||'Скопировано')}catch(e){notify('Не удалось скопировать','error')}}
function toggleLink(){const e=document.getElementById('link');e.type=e.type==='password'?'text':'password'}
function formatTime(iso){if(!iso)return '—';try{return new Date(iso).toLocaleString()}catch(e){return iso}}
function formatDuration(iso){if(!iso)return '—';const started=new Date(iso).getTime();if(!Number.isFinite(started))return '—';let sec=Math.max(0,Math.floor((Date.now()-started)/1000));const d=Math.floor(sec/86400);sec%=86400;const h=Math.floor(sec/3600);sec%=3600;const m=Math.floor(sec/60);const ss=sec%60;const parts=[];if(d)parts.push(d+' д');if(h||d)parts.push(h+' ч');if(m||h||d)parts.push(m+' мин');if(!d&&!h)parts.push(ss+' сек');return parts.join(' ')}
function encoderName(name){const x=encoderCapabilities.find(v=>v.name===name);return x?x.label:({'h264_qsv':'Intel Quick Sync · H.264','h264_nvenc':'NVIDIA NVENC · H.264','h264_amf':'AMD AMF · H.264','libx264':'Программный H.264','hevc_qsv':'Intel Quick Sync · H.265','hevc_nvenc':'NVIDIA NVENC · H.265','hevc_amf':'AMD AMF · H.265','libx265':'Программный H.265'})[name]||name||'—'}
function normalizeExitCode(raw){const n=Number(raw);if(!Number.isFinite(n))return null;return n>2147483647&&n<=4294967295?n-4294967296:n}
function exitCodeText(raw){const code=normalizeExitCode(raw);if(code===null||code===-1)return '';if(code===-32)return 'соединение закрыто сервером';if(code===0)return 'штатное завершение';return 'технический код '+code}
function openHistory(){const items=[...(lastStatus.restart_history||[])].reverse(),box=document.getElementById('historyList');box.innerHTML=items.length?items.map(x=>{const code=exitCodeText(x.exit_code);return '<div class="historyitem"><b>'+escapeHTML(x.reason)+'</b><div class="historytime">'+escapeHTML(formatTime(x.at))+(code?' · '+escapeHTML(code):'')+'</div></div>'}).join(''):'<div class="hint">Переподключений пока не было</div>';document.getElementById('historyModal').classList.remove('hidden')}
function closeHistory(){document.getElementById('historyModal').classList.add('hidden')}
function showLocalIPNotice(){document.getElementById('localIPModal').classList.remove('hidden')}
function closeLocalIPNotice(){document.getElementById('localIPModal').classList.add('hidden')}
async function status(){try{const s=await api('/api/status');lastStatus=s;document.getElementById('version').textContent='Версия '+s.version;const text=s.running?'поток работает':(s.desired?'подключение…':'поток остановлен');document.getElementById('statusText').textContent=text;const dot=document.getElementById('statusDot');dot.className='dot '+(s.running?'ok':s.desired?'wait':s.last_error?'bad':'');const hasAudio=currentConfig.audio_enabled||currentConfig.microphone_enabled;document.getElementById('bottomInfo').textContent=s.running?(hasAudio?'Изображение и звук передаются':'Изображение передаётся'):s.desired?'Выполняется подключение…':'Поток остановлен';let html='<div class="summary-row"><b>Состояние</b><span>'+escapeHTML(text)+'</span></div><div class="summary-row"><b>Источник</b><span>'+escapeHTML(s.capture_status||'—')+'</span></div>';if(s.video_encoder)html+='<div class="summary-row"><b>Кодировщик</b><span>'+escapeHTML(encoderName(s.video_encoder))+'</span></div>';if(s.running&&s.started_at)html+='<div class="summary-row"><b>Время работы</b><span>'+escapeHTML(formatDuration(s.started_at))+'</span></div>';html+='<div class="summary-row"><b>Переподключения</b><span>'+s.restarts+'</span></div>';if(s.last_restart_reason)html+='<div class="summary-row"><b>Последняя причина</b><span>'+escapeHTML(s.last_restart_reason)+'<br>'+escapeHTML(formatTime(s.last_restart_at))+'</span></div>';if((s.restart_history||[]).length)html+='<div class="summary-row"><b>Все причины</b><span><button class="btn link" type="button" onclick="openHistory()">Открыть список ('+s.restart_history.length+')</button></span></div>';document.getElementById('summary').innerHTML=html;document.getElementById('log').textContent=(s.recent_log||[]).join('\n')||'Журнал пуст';if(s.local_rtsp_url||s.local_rtsp_lan_url)applyLocalLinks(s.local_rtsp_url,s.local_rtsp_lan_url);const startButton=document.getElementById('startStreamButton'),stopButton=document.getElementById('stopStreamButton'),restartButton=document.getElementById('restartStreamButton');if(startButton)startButton.disabled=!!(s.running||s.desired);if(stopButton)stopButton.disabled=!s.running&&!s.desired;if(restartButton)restartButton.disabled=!s.running;const md=document.getElementById('micRuntimeDot'),mt=document.getElementById('micRuntimeText'),mb=document.getElementById('micLevelBar');if(md&&mt&&mb){const enabled=!!currentConfig.microphone_enabled;md.className='dot '+(!enabled?'':s.microphone_muted?'bad':s.microphone_active?'ok':'');mt.textContent=!enabled?'Микрофон выключен':s.microphone_muted?'Микрофон выключен горячей клавишей':s.microphone_active?'Микрофон активен':'Микрофон ожидает активации';mb.style.width=(enabled?Math.max(0,Math.min(100,Number(s.microphone_level||0))):0)+'%'}}catch(e){}}
function escapeHTML(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function load(){const results=await Promise.all([api('/api/config'),api('/api/monitors').catch(()=>[])]);monitorItems=results[1];applyConfig(results[0]);document.querySelectorAll('input[name="output_mode"]').forEach(x=>x.onchange=outputModeChanged);document.querySelectorAll('input[name="capture_mode"]').forEach(x=>x.onchange=captureChanged);document.getElementById('local_rtsp_port').addEventListener('blur',()=>checkLocalPort(false));bindDirtyTracking();await Promise.all([loadEncoderCapabilities(),loadAudioDevices()]);setBaseline();updateDirty();await status()}
load().catch(e=>notify(e.message,'error'));setInterval(status,2000);
</script>
</body></html>`
